spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-druid?serverTimezone=GMT
    username: root
    password: qaz@01
    platform: mysql

    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springboot-druid?serverTimezone=GMT
      username: root
      password: qaz@01
      initial-size: 20
      max-active: 20
      min-idle: 5
      max-wait: -1

      web-stat-filter:
        enabled: true
        url-pattern:
        exclusions:

      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable:
        login-username: admin
        login-password: admin
        allow:
        deny:
