spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-redis
    username: root
    password: qaz@01
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-idle: 20
        min-idle: 1
        max-wait: -1ms
    database: 0
